### ISSUE TITLE
Fixing content for marketing site v1

### ISSUE THREAD

**Issue by gsong** [hiai-labs/website#3]

**Comment by gsong** [comment]
@0xkc I've pared down the homepage for now. It still needs more work, obviously, but something we can progress.

Have you used <https://tailwindcss.com/docs/installation> for CSS?

**Comment by 0xkc** [comment]
> [@0xkc](https://github.com/0xkc) I've pared down the homepage for now. It still needs more work, obviously, but something we can progress.
> 
> Have you used https://tailwindcss.com/docs/installation for CSS?

@gsong it looks great as the first version. Thanks! Yes I've used tailwindcss before. We will make it ready for marketing by end of Q3.
