### ISSUE TITLE
logo & favicon by end of Q3

### ISSUE THREAD

**Issue by gsong** [hiai-labs/website#4]

**Comment by gsong** [comment]
Can you share these with me? Maybe we can use Google Drive to keep these type of collateral so we both have access?

**Comment by 0xkc** [comment]
> Can you share these with me? Maybe we can use Google Drive to keep these type of collateral so we both have access?

Shared to your google workspace account via Google Drive. One folder has logo file only (no favicon yet). The other folder has a few images for ProofOfQuest nft.
